modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="clockwork_tides"
version="1.0.0"
displayName="Clockwork Tides"
authors="scarrymany"
description='''Three precision-crafted fishing rods for Create. Fish the open waters for food, materials and recovered machinery.'''
[[dependencies.clockwork_tides]]
modId="neoforge"
type="required"
versionRange="[21.1.219,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.clockwork_tides]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.clockwork_tides]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="AFTER"
side="BOTH"
